name: Deployment

on:
  push:
    branches:
    - main
  
defaults:
  run:
    working-directory: backend
jobs:
  deploy:
    environment: Secrets
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Google App Engine
      uses: google-github-actions/deploy-appengine@v0
      with:
        project_id: job-application-tracker-361814
        working_directory: backend
        credentials: ${{secrets.GOOGLE_APP_ENGINE_KEY}}
        deliverables: app.yaml
        
