name: Deploy to Back4App
on:
  push:
    branches:
    - main
  
defaults:
  run:
    working-directory: backend/job-track-functions
jobs:
  deploy:
    environment: Secrets
    name: Deploy to Back4App
    runs-on: ubuntu-latest
    
    steps:
    - name: Automated Back4App B4a deployment
      # uses: rimonhanna/github-action-b4a-deploy@522814cdc5bcdc820d6782113c56eb4dffb57c2a
      uses: rimonhanna/github-action-b4a-deploy@v1.0.20
      with:
        # Back4App api key
        B4A_API_KEY: '${{ secrets.BACK4APP_ACCOUNT_KEY }}'
        # Name of the app to deploy to, deploys to default if left empty
        APP_NAME: job-track-functions
