name: Deployment

on:
  push:
    branches:
    - main
  
defaults:
  run:
    working-directory: backend
jobs:
  deploy:
    environment: Secrets
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_APP_ENGINE_JSON }}'
    - id: 'deploy'
      uses: google-github-actions/deploy-appengine@v0
      with:
        project_id: job-application-tracker-361814
        working_directory: backend
        deliverables: app.yaml
